package dev.kastrick.minesport.export;

import dev.kastrick.minesport.resolver.ResolverChain;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;

/**
 * Writes a .mtl material file alongside the OBJ export.
 * Extracts textures from the resolver chain and saves them as PNGs
 * next to the OBJ file, then references them in the MTL.
 */
public class MtlExporter {

    /**
     * Write a .mtl file for all texture paths used in the export.
     * Also extracts texture PNGs into a textures/ subfolder next to the OBJ.
     *
     * @param materials     all unique texture/tint combinations used
     * @param mtlFile       output .mtl file
     * @param resolvers     resolver chain to load textures from
     */
    public static void export(
            Set<MaterialKey> materials,
            File mtlFile,
            ResolverChain resolvers
    ) throws IOException {
        File texturesDir = new File(mtlFile.getParent(), "textures");
        texturesDir.mkdirs();

        try (PrintWriter w = new PrintWriter(new FileWriter(mtlFile))) {
            w.println("# Minesport MTL — generated by Kastrick's Minesport");
            w.println();

            for (MaterialKey material : materials) {
                String texPath = material.texturePath();
                if (texPath.startsWith("MISSING_")) {
                    // Fallback material — no texture
                    String matName = texPath.replace(':', '_').replace('/', '_');
                    w.println("newmtl " + matName);
                    w.println("Kd 0.5 0.0 0.5"); // purple = missing
                    w.println("Ka 0.1 0.0 0.1");
                    w.println("Ks 0.0 0.0 0.0");
                    w.println();
                    continue;
                }

                String matName = material.materialName();
                String pngName = matName + ".png";
                File pngFile = new File(texturesDir, pngName);

                // Always refresh generated assets. Re-exporting into the same
                // folder must not silently retain an older pack/tint texture.
                BufferedImage img = material.apply(resolvers.resolveTexture(texPath));
                if (img != null) {
                    ImageIO.write(img, "PNG", pngFile);
                }

                w.println("newmtl " + matName);
                if (pngFile.exists()) {
                    // Relative path from MTL to texture
                    w.println("map_Kd textures/" + pngName);
                    if (img != null && hasTransparency(img)) {
                        String alphaName = matName + "__alpha.png";
                        writeAlphaMap(img, new File(texturesDir, alphaName));
                        w.println("map_d textures/" + alphaName);
                    }
                }
                w.println("Kd 1.0 1.0 1.0");
                w.println("Ka 0.1 0.1 0.1");
                w.println("Ks 0.0 0.0 0.0");
                w.println("d 1.0");
                w.println("illum 1");
                w.println();
            }
        }
    }

    private static boolean hasTransparency(BufferedImage image) {
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                if ((image.getRGB(x, y) >>> 24) != 255) return true;
            }
        }
        return false;
    }

    private static void writeAlphaMap(BufferedImage source, File output) throws IOException {
        BufferedImage alpha = new BufferedImage(source.getWidth(), source.getHeight(), BufferedImage.TYPE_BYTE_GRAY);
        for (int y = 0; y < source.getHeight(); y++) {
            for (int x = 0; x < source.getWidth(); x++) {
                int a = (source.getRGB(x, y) >>> 24) & 0xff;
                int gray = (a << 16) | (a << 8) | a;
                alpha.setRGB(x, y, 0xff000000 | gray);
            }
        }
        ImageIO.write(alpha, "PNG", output);
    }
}
