package dev.kastrick.minesport.export;

import dev.kastrick.minesport.resolver.ResolverChain;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;

/**
 * Writes a .mtl material file alongside the OBJ export.
 * Extracts textures from the resolver chain and saves them as PNGs
 * next to the OBJ file, then references them in the MTL.
 */
public class MtlExporter {

    /**
     * Write a .mtl file for all texture paths used in the export.
     * Also extracts texture PNGs into a textures/ subfolder next to the OBJ.
     *
     * @param texturePaths  all unique texture paths used (e.g. "minecraft:block/oak_planks")
     * @param mtlFile       output .mtl file
     * @param resolvers     resolver chain to load textures from
     */
    public static void export(
            Set<String> texturePaths,
            File mtlFile,
            ResolverChain resolvers
    ) throws IOException {
        File texturesDir = new File(mtlFile.getParent(), "textures");
        texturesDir.mkdirs();

        try (PrintWriter w = new PrintWriter(new FileWriter(mtlFile))) {
            w.println("# Minesport MTL — generated by Kastrick's Minesport");
            w.println();

            for (String texPath : texturePaths) {
                if (texPath.startsWith("MISSING_")) {
                    // Fallback material — no texture
                    String matName = texPath.replace(':', '_').replace('/', '_');
                    w.println("newmtl " + matName);
                    w.println("Kd 0.5 0.0 0.5"); // purple = missing
                    w.println("Ka 0.1 0.0 0.1");
                    w.println("Ks 0.0 0.0 0.0");
                    w.println();
                    continue;
                }

                String matName = texPath.replace(':', '_').replace('/', '_');
                String pngName = matName + ".png";
                File pngFile = new File(texturesDir, pngName);

                // Extract texture PNG from resolver
                if (!pngFile.exists()) {
                    BufferedImage img = resolvers.resolveTexture(texPath);
                    if (img != null) {
                        ImageIO.write(img, "PNG", pngFile);
                    }
                }

                w.println("newmtl " + matName);
                if (pngFile.exists()) {
                    // Relative path from MTL to texture
                    w.println("map_Kd textures/" + pngName);
                    w.println("map_d  textures/" + pngName); // alpha channel for leaves etc
                }
                w.println("Kd 1.0 1.0 1.0");
                w.println("Ka 0.1 0.1 0.1");
                w.println("Ks 0.0 0.0 0.0");
                w.println("d 1.0");
                w.println("illum 1");
                w.println();
            }
        }
    }
}
