package dev.kastrick.minesport.export;

import dev.kastrick.minesport.resolver.ResolverChain;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.*;
import java.util.*;

/** Writes a .mtl file alongside OBJ exports and extracts referenced textures. */
public class MtlExporter {
    public static void export(
            Set<MaterialKey> materials,
            File mtlFile,
            ResolverChain resolvers
    ) throws IOException {
        File texturesDir = new File(mtlFile.getParent(), "textures");
        texturesDir.mkdirs();

        try (PrintWriter w = new PrintWriter(new FileWriter(mtlFile))) {
            w.println("# Minesport MTL — generated by Kastrick's Minesport");
            w.println();

            for (MaterialKey material : materials) {
                String texPath = material.texturePath();
                if (texPath.startsWith("MISSING_")) {
                    String matName = texPath.replace(':', '_').replace('/', '_');
                    w.println("newmtl " + matName);
                    w.println("Kd 0.5 0.0 0.5");
                    w.println("Ka 0.1 0.0 0.1");
                    w.println("Ks 0.0 0.0 0.0");
                    w.println();
                    continue;
                }

                String matName = material.materialName();
                String pngName = matName + ".png";
                File pngFile = new File(texturesDir, pngName);

                BufferedImage img = material.apply(resolvers.resolveTexture(texPath));
                if (img == null) img = missingTexture();
                ImageIO.write(img, "PNG", pngFile);

                w.println("newmtl " + matName);
                if (pngFile.exists()) {
                    w.println("map_Kd textures/" + pngName);
                    if (hasTransparency(img)) {
                        String alphaName = matName + "__alpha.png";
                        writeAlphaMap(img, new File(texturesDir, alphaName));
                        w.println("map_d textures/" + alphaName);
                    }
                }

                MaterialSemantics.Kind kind = MaterialSemantics.classify(texPath);
                w.println("Kd 1.0 1.0 1.0");
                w.println("Ka 0.1 0.1 0.1");
                if (kind == MaterialSemantics.Kind.WATER || kind == MaterialSemantics.Kind.GLASS) {
                    // MTL has no modern transmission model. Dissolve + specular
                    // gives OBJ importers a useful transparent fallback while
                    // Minesport's Blender translator upgrades it to Principled
                    // transmission after import.
                    w.println("Ks 0.35 0.35 0.35");
                    w.printf(Locale.ROOT, "Ns %.1f%n", kind == MaterialSemantics.Kind.GLASS ? 220.0 : 120.0);
                    w.printf(Locale.ROOT, "d %.3f%n", MaterialSemantics.dissolve(texPath));
                    w.println("illum 4");
                } else {
                    w.println("Ks 0.0 0.0 0.0");
                    w.println("d 1.0");
                    w.println("illum 1");
                }
                w.println();
            }
        }
    }

    private static boolean hasTransparency(BufferedImage image) {
        for (int y = 0; y < image.getHeight(); y++) {
            for (int x = 0; x < image.getWidth(); x++) {
                if ((image.getRGB(x, y) >>> 24) != 255) return true;
            }
        }
        return false;
    }

    private static void writeAlphaMap(BufferedImage source, File output) throws IOException {
        BufferedImage alpha = new BufferedImage(source.getWidth(), source.getHeight(), BufferedImage.TYPE_BYTE_GRAY);
        for (int y = 0; y < source.getHeight(); y++) {
            for (int x = 0; x < source.getWidth(); x++) {
                int a = (source.getRGB(x, y) >>> 24) & 0xff;
                int gray = (a << 16) | (a << 8) | a;
                alpha.setRGB(x, y, 0xff000000 | gray);
            }
        }
        ImageIO.write(alpha, "PNG", output);
    }

    private static BufferedImage missingTexture() {
        BufferedImage image = new BufferedImage(16, 16, BufferedImage.TYPE_INT_ARGB);
        for (int y = 0; y < 16; y++) {
            for (int x = 0; x < 16; x++) {
                boolean alternate = ((x / 4) + (y / 4)) % 2 == 0;
                image.setRGB(x, y, alternate ? 0xffff00ff : 0xff2a002a);
            }
        }
        return image;
    }
}
