maven_group=dev.kastrick
mod_version=0.2.0
archives_base_name=minesport-bridge-quilt
minecraft_version=1.21.10
quilt_loader_version=0.30.1-beta.3
fabric_version=0.138.4+1.21.10
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:ActiveProcessorCount=2 -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false
