# Mod metadata
maven_group=dev.kastrick
mod_version=0.1.0
archives_base_name=minesport-bridge

# Minecraft + Fabric versions (legacy bridge)
minecraft_version=1.21.10
loader_version=0.18.5
fabric_version=0.138.4+1.21.10

# Polymer (optional)
polymer_version=0.14.4+1.21.10

# Java
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
