mod_id=minesport_bridge
mod_name=Minesport Bridge
mod_group_id=dev.kastrick
mod_version=0.2.0
archives_base_name=minesport-bridge-neoforge
minecraft_version=1.21.10
minecraft_version_range=[1.21.10,1.21.11)
neo_version=21.10.64
org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=384m -XX:ActiveProcessorCount=2 -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.vfs.watch=false
