package main

import (
    "encoding/base64"
    "flag"
    "fmt"
    "os"
)

func main() {
    input := flag.String("input", "", "engine JAR to embed")
    output := flag.String("output", "embedded_engine_generated.go", "generated Go source path")
    flag.Parse()

    if *input == "" || *output == "" {
        panic("usage: embed-engine -input <jar> -output <go-file>")
    }

    data, err := os.ReadFile(*input)
    if err != nil {
        panic(err)
    }

    encoded := base64.StdEncoding.EncodeToString(data)
    source := fmt.Sprintf(`// Code generated by cmd/embed-engine; DO NOT EDIT.
//go:build minesport_embedded_engine

package main

import "encoding/base64"

const embeddedEngineBase64 = %q

func embeddedEngineBytes() []byte {
    data, err := base64.StdEncoding.DecodeString(embeddedEngineBase64)
    if err != nil {
        return nil
    }
    return data
}
`, encoded)

    if err := os.WriteFile(*output, []byte(source), 0644); err != nil {
        panic(err)
    }
}
