package ui

import("bufio";"encoding/json";"fmt";"io";"os";"os/exec";"sync";"fyne.io/fyne/v2/dialog";"fyne.io/fyne/v2/theme";"github.com/kastrick/minesport/ipc")

type ViewerEvent struct{Type string `json:"type"`;X,Y,Z int `json:"x"`;Blocks [][3]int `json:"blocks"`;Min [3]int `json:"min"`;Max [3]int `json:"max"`;Count int `json:"count"`;Message string `json:"message"`}
type ViewerSession struct{cmd *exec.Cmd;stdin io.WriteCloser;mu sync.Mutex;OnReady func(int);OnError func(string);OnPick func(int,int,int);OnSelection func([][3]int,int);OnBoxSelected func([3]int,[3]int,int);OnClosed func()}
func LaunchViewer(exePath,blocksPath string)(*ViewerSession,error){cmd:=exec.Command(exePath,"--viewer",blocksPath);in,err:=cmd.StdinPipe();if err!=nil{return nil,err};out,err:=cmd.StdoutPipe();if err!=nil{return nil,err};if err=cmd.Start();err!=nil{return nil,err};vs:=&ViewerSession{cmd:cmd,stdin:in};go vs.readLoop(out);go func(){cmd.Wait();if vs.OnClosed!=nil{vs.OnClosed()}}();return vs,nil}
func(vs *ViewerSession)readLoop(stdout io.Reader){s:=bufio.NewScanner(stdout);s.Buffer(make([]byte,0,64*1024),8*1024*1024);for s.Scan(){var ev ViewerEvent;if json.Unmarshal([]byte(s.Text()),&ev)!=nil{continue};switch ev.Type{case"ready":if vs.OnReady!=nil{vs.OnReady(ev.Count)};case"error":if vs.OnError!=nil{vs.OnError(ev.Message)};case"pick":if vs.OnPick!=nil{vs.OnPick(ev.X,ev.Y,ev.Z)};case"selection":if vs.OnSelection!=nil{vs.OnSelection(ev.Blocks,ev.Count)};case"boxSelected":if vs.OnBoxSelected!=nil{vs.OnBoxSelected(ev.Min,ev.Max,ev.Count)}}}}
func(vs *ViewerSession)send(cmd map[string]interface{}){vs.mu.Lock();defer vs.mu.Unlock();if vs.stdin==nil{return};b,_:=json.Marshal(cmd);fmt.Fprintln(vs.stdin,string(b))}
func(vs *ViewerSession)FloodFill(x,y,z,power int){vs.send(map[string]interface{}{"command":"floodFill","x":x,"y":y,"z":z,"power":power})};func(vs *ViewerSession)HighlightBox(min,max [3]int){vs.send(map[string]interface{}{"command":"highlightBox","min":min,"max":max})};func(vs *ViewerSession)ClearHighlight(){vs.send(map[string]interface{}{"command":"clearHighlight"})};func(vs *ViewerSession)Close(){vs.send(map[string]interface{}{"command":"quit"})}

func(ms *MinesportApp)onExplore3D(){
	if ms.worldPath==""{dialog.ShowError(fmt.Errorf("select a world first"),ms.window);return};if ms.viewerSession!=nil{return};ms.statusLabel.SetText("Loading 3D preview…");ms.stateIcon.SetResource(theme.ViewRefreshIcon())
	go func(){p:=ipc.ListBlocksParams{WorldPath:ms.worldPath};if ms.selectionModeSelect.Selected=="Bubble selection"{cx,cy,cz:=ms.centerX.Int(0),ms.centerY.Int(64),ms.centerZ.Int(0);rx,ry,rz:=ms.radiusX.Int(32),ms.radiusY.Int(32),ms.radiusZ.Int(32);p.MinX,p.MaxX=cx-rx,cx+rx;p.MinY,p.MaxY=cy-ry,cy+ry;p.MinZ,p.MaxZ=cz-rz,cz+rz;p.CenterX,p.CenterY,p.CenterZ=&cx,&cy,&cz;p.RadiusX,p.RadiusY,p.RadiusZ=&rx,&ry,&rz}else{p.MinX,p.MaxX=ms.minXRange.Bounds();p.MinY,p.MaxY=ms.minYRange.Bounds();p.MinZ,p.MaxZ=ms.minZRange.Bounds()};path,count,err:=ms.engine.ListBlocks(p);if err!=nil{ms.explore3DFailed(err.Error());return};if count==0{return};exe,err:=os.Executable();if err!=nil{ms.explore3DFailed(err.Error());return};s,err:=LaunchViewer(exe,path);if err!=nil{ms.explore3DFailed(err.Error());return};ms.viewerSession=s;s.OnReady=func(n int){ms.statusLabel.SetText(fmt.Sprintf("3D ready · %s blocks",formatCount(n)));ms.stateIcon.SetResource(theme.ConfirmIcon())};s.OnError=func(msg string){ms.explore3DFailed("3D viewer error: "+msg)};s.OnPick=func(x,y,z int){ms.showSelectionPopup(x,y,z)};s.OnSelection=func(blocks [][3]int,count int){ms.updateMetaHUD(fmt.Sprintf("%s joined blocks selected",formatCount(count)))};s.OnBoxSelected=func(min,max [3]int,count int){ms.applyBoxSelectionFromViewer(min,max,count)};s.OnClosed=func(){ms.viewerSession=nil;ms.statusLabel.SetText("Ready");ms.stateIcon.SetResource(theme.InfoIcon())}}()
}
func(ms *MinesportApp)explore3DFailed(msg string){ms.statusLabel.SetText("Ready");ms.stateIcon.SetResource(theme.InfoIcon());dialog.ShowError(fmt.Errorf("%s",msg),ms.window)}
func(ms *MinesportApp)applyBoxSelectionFromViewer(min,max [3]int,count int){ms.customSelectionFile="";ms.customSelectionCount=0;ms.minXRange.Front.SetText(fmt.Sprintf("%d",min[0]));ms.minXRange.Back.SetText(fmt.Sprintf("%d",max[0]));ms.minYRange.Front.SetText(fmt.Sprintf("%d",min[1]));ms.minYRange.Back.SetText(fmt.Sprintf("%d",max[1]));ms.minZRange.Front.SetText(fmt.Sprintf("%d",min[2]));ms.minZRange.Back.SetText(fmt.Sprintf("%d",max[2]));ms.updateMetaHUD(fmt.Sprintf("%s blocks selected · 3D",formatCount(count)))}
