[package]
name = "minesport-desktop"
version = "0.2.0"
edition = "2024"
rust-version = "1.92"
build = "build.rs"

[[bin]]
name = "minesport"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
base64 = "=0.22.1"
image = { version = "=0.25.8", default-features = false, features = ["png"] }
include_dir = "=0.7.4"
regex = "=1.12.2"
rfd = "=0.17.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "=0.10.9"
slint = { version = "=1.17.1", default-features = false, features = ["std", "compat-1-2", "backend-winit", "renderer-femtovg", "renderer-software", "accessibility"] }
ureq = { version = "=2.12.1", default-features = false, features = ["tls"] }

[build-dependencies]
slint-build = "=1.17.1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = true
panic = "abort"
